// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjvgohomwhsrjnmylscb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqdmdvaG9td2hzcmpubXlsc2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTM3MTEsImV4cCI6MjA1NzYyOTcxMX0.1UFWRZmrBWeUNyhoaI6UGRKJgDCqa276efogcGpfIQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);